language: python
python: 2.7
node_js:
  - "6"
install: "pip install Lektor"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install -g gulp bower
  - npm install
  - bower install
before_script:
  - gulp build
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy ghpages"
